### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by RM1978** [canada-ca/a11y#38] opened 2021-01-25 17:55 UTC
Hi , 

I am writing today because I cannot access the tools that you have made available this section: Designing accessible services. It would seem that my credenetials don’t work for this part of the sites, but I wonder if I could have access to the Designing for screen reader users section in particular?

Many thanks !

Best, 

RM1978

**Comment by nschonni** [comment] 2021-01-25 18:23
Duplicate of #35

**Closed as completed by nschonni** 2021-01-25 18:23 UTC
Labels: bug
